# Generated by Django 4.2.5 on 2023-10-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_options_alter_tasks_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
